version: '3.8'
services:
  relay:
    build: .
    image: "${IMAGE_NAME:-girino/khatru-relay:rc2}"
    container_name: "${CONTAINER_NAME:-khatru-relay}"
    restart: unless-stopped
    # Load variables from .env in repo root; docker-compose also reads .env automatically,
    # but specifying env_file keeps intent explicit and works for some CI setups.
    env_file: .env
    environment:
      # Force the internal listener address to :3337 (container-internal).
      ADDR: ":3337"
      RELAY_NAME: "${RELAY_NAME:-Espelho de São Miguel}"
    # Use COMPOSE_RELAY_PORT to control the host port mapping. Container listens on 3337.
    ports:
      - "${COMPOSE_RELAY_PORT:-3337}:3337" # host:container
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3337/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
