version: '3.8'
services:
  relay:
    build: .
    image: "${IMAGE_NAME:-girino/khatru-relay:rc2}"
    container_name: "${CONTAINER_NAME:-khatru-relay}"
    restart: unless-stopped
    # Load variables from .env in repo root; docker-compose also reads .env automatically,
    # but specifying env_file keeps intent explicit and works for some CI setups.
    env_file: .env
    environment:
      RELAY_PORT: "${RELAY_PORT:-3337}"
      RELAY_NAME: "${RELAY_NAME:-Espelho de São Miguel}"
    ports:
      - "${RELAY_PORT:-3337}:${RELAY_PORT:-3337}" # HTTP/NIP-11/homepage
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${RELAY_PORT:-3337}/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
