version: '3.8'
services:
  relay:
    build: .
    image: girino/khatru-relay:rc2
    container_name: khatru-relay
    restart: unless-stopped
    environment:
      - RELAY_PORT=8080
      - RELAY_NAME=Espelho de São Miguel
    ports:
      - "8080:8080" # HTTP/NIP-11/homepage
    volumes:
      - ./config:/etc/khatru-relay:ro
      - ./data:/var/lib/khatru-relay
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
