name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v ./...

    - name: Build application
      run: go build -o bin/saint-michaels-mirror ./cmd/saint-michaels-mirror

    - name: Test Docker build (AMD64)
      run: |
        # Test AMD64 build (native architecture for GitHub Actions runners)
        docker build --build-arg GOARCH=amd64 -t saint-michaels-mirror:test .

    - name: Test Docker run
      run: |
        # Test the Docker container runs correctly
        docker run -d --name test-relay -p 3338:3337 saint-michaels-mirror:test
        sleep 5
        curl -f http://localhost:3338/.well-known/nostr.json || exit 1
        docker stop test-relay
        docker rm test-relay

    - name: Test cross-compilation builds
      run: |
        # Test that we can build for other architectures (without running them)
        echo "Testing ARM64 build..."
        docker build --build-arg GOARCH=arm64 -t saint-michaels-mirror:test-arm64 .
        echo "ARM64 build successful"
        
        # Test that the binary exists and has correct permissions
        docker run --rm saint-michaels-mirror:test-arm64 ls -la ./saint-michaels-mirror
        echo "Cross-compilation test completed successfully"
