name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v ./...

    - name: Build application
      run: go build -o bin/saint-michaels-mirror ./cmd/saint-michaels-mirror

    - name: Test Docker build (multi-architecture)
      run: |
        # Test AMD64 build
        docker build --build-arg GOARCH=amd64 -t saint-michaels-mirror:test-amd64 .
        # Test ARM64 build
        docker build --build-arg GOARCH=arm64 -t saint-michaels-mirror:test-arm64 .

    - name: Test Docker run (AMD64)
      run: |
        docker run -d --name test-relay-amd64 -p 3338:3337 saint-michaels-mirror:test-amd64
        sleep 5
        curl -f http://localhost:3338/.well-known/nostr.json || exit 1
        docker stop test-relay-amd64
        docker rm test-relay-amd64

    - name: Test Docker run (ARM64)
      run: |
        docker run -d --name test-relay-arm64 -p 3339:3337 saint-michaels-mirror:test-arm64
        sleep 5
        curl -f http://localhost:3339/.well-known/nostr.json || exit 1
        docker stop test-relay-arm64
        docker rm test-relay-arm64
